using Xunit;

namespace AxonIQ.AxonServer.Connector.IntegrationTests.Containerization;

[CollectionDefinition(nameof(ToxicAxonServerWithAccessControlDisabledCollection))]
public class ToxicAxonServerWithAccessControlDisabledCollection : ICollectionFixture<ToxicAxonServerWithAccessControlDisabled>
{
}