@startuml AxonServerConnection state machine
[*] --> Disconnected
Disconnected-->Disconnected: WaitUntilConnected \n WaitUntilReady \n CheckReadiness
Disconnected-->Connecting: Connect(Attempt = 0) / GrpcChannelEstablished
Connecting-->Connecting: Connect / GrpcChannelEstablished \n GrpcChannelEstablished(Ok) [channel == null] / Schedule(Connect(Attempt+1)) \n GrpcChannelEstablished(Error) / Schedule(Connect(Attempt+1)) \n WaitUntilConnected \n WaitUntilReady \n CheckReadiness
Connecting-->Connected: GrpcChannelEstablished(Ok) [channel <> null] / ConnectControlChannel, OnConnected, CheckReadiness
Connected-->Reconnecting: Reconnect((Attempt = 0) / GrpcChannelEstablished
Reconnecting-->Reconnecting: Reconnect / GrpcChannelEstablished \n GrpcChannelEstablished(Ok) [channel == null] / Reconnect(Attempt+1) \n GrpcChannelEstablished(Error) / Reconnect(Attempt+1) \n WaitUntilConnected \n WaitUntilReady \n CheckReadiness
Reconnecting-->Connected: GrpcChannelEstablished(Ok) [channel <> null] / ReconnectChannels, OnConnected, CheckReadiness
Connected-->Connected: ConnectControlChannel \n ReconnectChannels \n WaitUntilConnected \n WaitUntilReady \n OnConnected \n CheckReadiness
Connected --> [*]: Close
Connecting --> [*]: Close
Reconnecting --> [*]: Close
@enduml