@startuml Heartbeat Monitor
[*]->Disabled
Disabled-->Enabled: Enable
Enabled-->Paused: Pause
Paused->Enabled: Enable, Resume
Paused->Disabled: Disable
Enabled->Disabled: Disable
Disabled->Disabled: Disable, Resume, Pause
Enabled->Enabled: Enable, Resume
Paused->Paused: Pause
Enabled->Enabled: Check, CheckSucceeded, CheckFailed, ReceiveServerHeartbeat
@enduml