name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      # setup dotnet based on global.json
      - uses: actions/setup-dotnet@v3.0.2
      # run the CI build
      - name: make ci
        run: make ci
        env:
          AXONIQ_LICENSE: ${{ secrets.AXONIQ_LICENSE }}
      # run the CD build (on master only)
      - name: make cd
        if: github.ref == 'refs/heads/master'
        run: make cd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            test/AxonIQ.AxonServer.Connector.Tests/TestResults/*.trx
            test/AxonIQ.AxonServerIntegrationTests/TestResults/*.trx
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=axoniq
            -Dsonar.projectKey=AxonIQ_axonserver-connector-dotnet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}