name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # composed axonservers
      axonserver-with-accesscontrol-disabled:
        image: axoniq/axonserver:latest
        ports:
          - 8024:8024
          - 8124:8124
        env:
          AXONIQ_AXONSERVER_NAME: axonserver
          AXONIQ_AXONSERVER_HOSTNAME: localhost
          AXONIQ_AXONSERVER_DEVMODE_ENABLED: true
          AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED: false
        options: --name axonserver-with-accesscontrol-disabled-connector-dotnet-tests
      axonserver-with-accesscontrol-enabled:
        image: axoniq/axonserver:latest
        ports:
          - 8224:8024
          - 8324:8124
        env:
          AXONIQ_AXONSERVER_NAME: axonserver
          AXONIQ_AXONSERVER_HOSTNAME: localhost
          AXONIQ_AXONSERVER_DEVMODE_ENABLED: true
          AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED: true
          AXONIQ_AXONSERVER_ACCESSCONTROL_TOKEN: E@syP@ssw0rd
        options: --name axonserver-with-accesscontrol-enabled-connector-dotnet-tests
    steps:
      # checkout the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      # setup dotnet based on global.json
      - uses: actions/setup-dotnet@v1
      # run the CI build
      - name: make ci
        run: make ci
        env:
          CI: true # I'd assume this is present by default (need to verify)
          AXONIQ_AXONSERVER_ACCESSCONTROL_DISABLED_PORT: 8024
          AXONIQ_AXONSERVER_ACCESSCONTROL_DISABLED_GRPC_PORT: 8124
          AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED_PORT: 8224
          AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED_GRPC_PORT: 8324
          AXONIQ_AXONSERVER_ACCESSCONTROL_TOKEN: E@syP@ssw0rd
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=axoniq
            -Dsonar.projectKey=AxonIQ_axonserver-connector-dotnet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}