name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      # setup dotnet based on global.json
      - uses: actions/setup-dotnet@v2
      # run the CI build
      - name: make ci
        run: make ci
        env:
          AXONIQ_LICENSE: ${{ secrets.AXONIQ_LICENSE }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=axoniq
            -Dsonar.projectKey=AxonIQ_axonserver-connector-dotnet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}